"""index sessions.project_id for the project session list

Phase 1 turned the `sessions` table from a declared-but-unused schema into the
filing index behind Projects, and that made `project_id` an access path rather
than just a foreign key. Three routes filter on it: the per-project session
list, the session count shown per project in the library, and the sweep that
unfiles every session when a project is deleted.

The only other Phase 1 lookup -- "is this stored session filed, and where?" for
`GET /api/sessions` -- is already served by the
`uq_sessions_runtime_runtime_session_id` unique constraint's index, so this is
the one query shape that had nothing.

**This adds no column.** Everything Projects and filing need was already in the
schema at `d80d10a6908c`: `projects` (title, description, timestamps) and
`sessions` (project_id, runtime, runtime_session_id, title, status). Confirmed
with `alembic check` against head before writing anything -- "No new upgrade
operations detected" -- so nothing here was invented to give the feature a
migration.

Revision ID: 3cddea4c8cf6
Revises: d80d10a6908c
Create Date: 2026-08-30 02:13:19.360901+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cddea4c8cf6'
down_revision: Union[str, None] = 'd80d10a6908c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index('ix_sessions_project_id', ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_sessions_project_id')

    # ### end Alembic commands ###
