"""add background_tasks ledger

P2-1 (fixes B-42). The gateway's ledger of `prompt.background` tasks -- the
only durable record such a task ever existed, because Hermes keeps nothing
(PV "Phase 2 probe", 2026-08-30: no transcript row, no pollable status, one
un-replayed `background.complete` event, and a background-only session is
never persisted at all).

Column notes, matching `domain/models.py::BackgroundTask`:

* `task_id` (PK) is Hermes's own `bg_` + 6-hex id -- the completion event
  carries `{task_id, text}` and nothing else, so it is the only join key
  that exists. A documented exception to "runtime ids are never workspace
  primary keys"; the writer upserts because 6 hex chars is a small space.
* `stored_session_id` is the durable Hermes session id recorded at SUBMIT
  time (the completion frame is stamped with only a live handle). Nullable
  only for completions observed without a matching submit.
* `state` is running | finished | orphaned. Orphaned = "a gateway restart or
  Hermes reconnect happened while running; outcome unknown" -- measured as
  the default across a reconnect (PV "Phase 2a probes": completion delivered
  only to attached connections, 3/3 lost on a bare reconnect, rescuable by a
  pre-completion re-resume, 2/2).
* `result_text` holds the completion's `text` -- the only copy anywhere.
* `connection_generation` is the adapter's counter at submit; diagnostic
  context for orphaned rows, never used for resolution.

Both indexes are access paths, not decoration: the per-session list /
transcript injection filter on `stored_session_id`; the startup orphan sweep
and the reconnect rescue filter on `state`.

Autogenerated against a scratch DB at head `3cddea4c8cf6` ("No new upgrade
operations detected" after this file), then annotated.

Revision ID: 65478a8a907b
Revises: 3cddea4c8cf6
Create Date: 2026-08-30 15:56:09.837273+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65478a8a907b'
down_revision: Union[str, None] = '3cddea4c8cf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('background_tasks',
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('stored_session_id', sa.String(), nullable=True),
    sa.Column('prompt_text', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('result_text', sa.Text(), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('connection_generation', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('task_id')
    )
    with op.batch_alter_table('background_tasks', schema=None) as batch_op:
        batch_op.create_index('ix_background_tasks_state', ['state'], unique=False)
        batch_op.create_index('ix_background_tasks_stored_session_id', ['stored_session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('background_tasks', schema=None) as batch_op:
        batch_op.drop_index('ix_background_tasks_stored_session_id')
        batch_op.drop_index('ix_background_tasks_state')

    op.drop_table('background_tasks')
    # ### end Alembic commands ###
