"""artifact ingestion schema

P3-1.0. The `artifacts` table has existed since the initial schema but
nothing ever wrote it; as specced it cannot support Phase 3's ingestion
(`domain/models.py::Artifact` carries the full rationale). Four changes:

* `artifacts.project_id` NOT NULL -> nullable, mirroring exactly how P2-2
  (`cc25d09cd72c`) relaxed `runs.project_id`. An artifact's project comes
  from the workspace Session row *filing* its Hermes session, and filing is
  optional -- unfiled spike sessions are this project's standard test path
, so the first live P3-1 ingestion against a real spike session
  would crash on the NOT NULL constraint. NULL = "unfiled", the same answer
  `runs.project_id` and `GET /api/sessions` give; the synthetic-"unfiled"-
  project alternative stays rejected for the same P2-2d reasons.
* `artifacts.storage_key` NOT NULL -> nullable. An `unavailable` artifact
  was never fetched, so it has no storage key yet.
* `artifacts.status` (new; `available` / `unavailable`, server default
  `available` so existing rows -- and any writer that doesn't set it --
  read as available). `unavailable` is P3-1's designed failure path: a
  structured file signal whose bytes could not be fetched.
* `artifacts.source_path` (new, indexed) -- the absolute Hermes sandbox path
  the bytes were fetched from. `ix_artifacts_source_path` serves the "was
  this already ingested" dedup lookup and a future refresh/re-fetch;
  without the column neither is queryable.

Downgrade note: re-tightening `project_id`/`storage_key` to NOT NULL cannot
keep rows this feature wrote for unfiled sessions or unavailable artifacts,
so the downgrade deletes artifacts with a NULL `project_id` or NULL
`storage_key` (and their `artifact_links`) first -- the same class of
data-shedding downgrade as `cc25d09cd72c`'s NULL-project run shedding. Such
rows are re-ingestable from the sandbox via `source_path` as long as the
sandbox file still exists; nothing else references them.

Autogenerated against a scratch DB at head `cc25d09cd72c` (`alembic check`:
"No new upgrade operations detected" after this file), then annotated.

Revision ID: c7d841c7d3a9
Revises: cc25d09cd72c
Create Date: 2026-08-31 03:02:19.193270+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7d841c7d3a9'
down_revision: Union[str, None] = 'cc25d09cd72c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), server_default='available', nullable=False))
        batch_op.add_column(sa.Column('source_path', sa.String(), nullable=True))
        batch_op.alter_column('project_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('storage_key',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_index('ix_artifacts_source_path', ['source_path'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # Rows written for unfiled sessions (NULL project_id) or never-fetched
    # artifacts (NULL storage_key) cannot survive the NOT NULL
    # re-tightening -- shed them (and their links) first so the downgrade is
    # clean rather than a constraint failure. See the module docstring's
    # downgrade note.
    op.execute(
        "DELETE FROM artifact_links WHERE artifact_id IN "
        "(SELECT id FROM artifacts WHERE project_id IS NULL OR storage_key IS NULL)"
    )
    op.execute(
        "DELETE FROM artifacts WHERE project_id IS NULL OR storage_key IS NULL"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.drop_index('ix_artifacts_source_path')
        batch_op.alter_column('storage_key',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('project_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('source_path')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
