"""run attribution and event log

P2-2. The `runs`/`run_events` tables have existed since the initial schema
but nothing ever wrote them -- `persist_event` had zero live call sites and
the broadcaster stamped placeholder attribution ids. This migration is the
schema half of making them real (`api/runs.py::RunRecorder` is the writer):

* `runs.runtime_session_id` (new, indexed) -- the Hermes **STORED / durable**
  session id, recorded at run open. Never a live handle (the two-id-spaces
  rule, `domain/models.py::Session`). This is the attribution that always
  exists: workspace `session_id`/`project_id` come from the *filing* lookup
  and are NULL for every unfiled session, but a run still names the Hermes
  session it belongs to, so `GET /api/runs?session=<stored id>` works for
  spike sessions too.
* `runs.project_id` NOT NULL -> nullable (P2-2d decision). A run's project
  comes from the workspace Session row filing its Hermes session, and filing
  is optional -- most real sessions have no Session row. NULL = "unfiled",
  the same answer `GET /api/sessions` already gives. The synthetic-"unfiled"-
  project alternative was rejected: it would surface a fake project in the
  Project Library, break its session counts, and give "delete project =
  unfile everything" an undefined meaning.
* `ix_runs_runtime_session_id` / `ix_runs_project_id` -- the two
  `GET /api/runs` filters (P2-2e).
* `ix_run_events_run_id_seq` -- the one event read path:
  `GET /api/runs/{id}/events?after_seq=` filters on `run_id` + `seq` and
  orders by `seq`. `run_events.seq` is the per-run, restart-surviving cursor
  (P2-2c); nothing here or in the writer touches the process-local global
  stream counter, which resets on restart and must never be a durable cursor.

Downgrade note: re-tightening `project_id` to NOT NULL cannot keep rows this
feature wrote for unfiled sessions, so the downgrade deletes runs with a
NULL `project_id` (and their `run_events`) first -- the same class of
data-shedding downgrade as dropping the background_tasks table one revision
earlier. Run history is observational and regenerable by watching new turns;
nothing else references these rows.

Autogenerated against a scratch DB at head `65478a8a907b` (`alembic check`:
"No new upgrade operations detected" after this file), then annotated.

Revision ID: cc25d09cd72c
Revises: 65478a8a907b
Create Date: 2026-08-30 16:12:14.645618+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc25d09cd72c'
down_revision: Union[str, None] = '65478a8a907b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('run_events', schema=None) as batch_op:
        batch_op.create_index('ix_run_events_run_id_seq', ['run_id', 'seq'], unique=False)

    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('runtime_session_id', sa.String(), nullable=True))
        batch_op.alter_column('project_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_index('ix_runs_project_id', ['project_id'], unique=False)
        batch_op.create_index('ix_runs_runtime_session_id', ['runtime_session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # Rows written for unfiled sessions carry NULL project_id and cannot
    # survive the NOT NULL re-tightening -- shed them (and their events)
    # first so the downgrade is clean rather than a constraint failure.
    # See the module docstring's downgrade note.
    op.execute(
        "DELETE FROM run_events WHERE run_id IN "
        "(SELECT id FROM runs WHERE project_id IS NULL)"
    )
    op.execute("DELETE FROM runs WHERE project_id IS NULL")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index('ix_runs_runtime_session_id')
        batch_op.drop_index('ix_runs_project_id')
        batch_op.alter_column('project_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('runtime_session_id')

    with op.batch_alter_table('run_events', schema=None) as batch_op:
        batch_op.drop_index('ix_run_events_run_id_seq')

    # ### end Alembic commands ###
