"""split hermes stored vs live session ids

Stop conflating the runtime's two session id spaces (docs/PROTOCOL_VERIFIED.md,
"Session resume & the two id spaces", verified live 2026-08-29):

- `sessions.runtime_session_id` keeps its name and now means, unambiguously,
  the **STORED / durable** id (Hermes `session.list` -> `id`). Existing rows
  need no data migration: nothing had been written to this column yet, and its
  intended meaning was always the durable mapping.
- `sessions.runtime_live_session_id` is new, nullable: the **LIVE / ephemeral**
  handle, a cache only, invalid across a Hermes restart or gateway reconnect.
  Deliberately un-indexed and un-constrained so it cannot become a lookup key.
- unique (runtime, runtime_session_id): one workspace Session per stored
  runtime session per runtime. NULLs stay distinct, so unbound sessions are
  unaffected.

Revision ID: d80d10a6908c
Revises: 261bd8308291
Create Date: 2026-08-29 18:38:13.488117+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd80d10a6908c'
down_revision: Union[str, None] = '261bd8308291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('runtime_live_session_id', sa.String(), nullable=True))
        batch_op.create_unique_constraint('uq_sessions_runtime_runtime_session_id', ['runtime', 'runtime_session_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_constraint('uq_sessions_runtime_runtime_session_id', type_='unique')
        batch_op.drop_column('runtime_live_session_id')

    # ### end Alembic commands ###
